# Generated by Django 3.1.1 on 2020-09-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0004_remove_movies_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='rating',
        ),
        migrations.AddField(
            model_name='movies',
            name='imdb_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='popularity',
            field=models.FloatField(null=True),
        ),
    ]
