# Generated by Django 3.1.1 on 2020-09-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0006_auto_20200911_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
